### ISSUE TITLE
Content Security Policy error in Firefox extension

### ISSUE THREAD

**Issue by geeknees** [textlint/editor#37]
Thank you for developing such a great extension.
I'm using Firefox and it seems to be stuck on the Content Security Policy issue and the worker doesn't work properly.

In the console of Service Workers, I am getting the following error.
```
Content Security Policy: ページの設定により次のリソースの読み込みをブロックしました: blob:moz-extension://131dce08-cad1-0f4e-a2d1-bbaa135d5fd6/dbb9e923-6275-c845-9fb4-5b9956a48008 (“script-src”)
```

Is there any way to solve this problem?

I know that there is a workaround to turn off the CSP for your entire browser in Firefox by disabling security.csp.enable in the about:config menu.

**Comment by azu** [comment]
Fmm, This error caused by this line

https://github.com/textlint/editor/blob/a65599a15ad341710c88778de5aa4a637c9107c2/packages/webextension/app/scripts/contentScript.ts#L17-L20

ContentScript does not support Web Components and I used an Injection script for avoiding.

https://bugs.chromium.org/p/chromium/issues/detail?id=390807
https://bugzilla.mozilla.org/show_bug.cgi?id=1492002

**Comment by azu** [comment]
Ah, I missed.

This error is caused by WebWorker in background.
https://github.com/textlint/editor/blob/6fbef2e8ba5c09819562f5d426d2a89b401bf010/packages/webextension/app/scripts/background/textlint.ts#L51-L56

Probably, We can resolve this issue by moving textlint script worker to CotentScript.
#33 is related.

**Comment by geeknees** [comment]
Thanks for the quick confirmation.
I'm glad that there seems to be a solution somehow.

I'm not familiar with extention and WebWorker, so I don't know if I can help, but I'll take a look at it myself.

**Comment by azu** [comment]
I've moved WebWorker to ContentScript from BackgroundScript and I've met another problem.
Some website like GitHub use CSP that block ContentScript's web worker...

![image](https://user-images.githubusercontent.com/19714/116435080-f5082300-a885-11eb-94ab-242ffa4b3282.png)

Work on no-CSP website

![image](https://user-images.githubusercontent.com/19714/116435624-87a8c200-a886-11eb-98d3-86462e0c139e.png)

I'll investigate `content_security_policy`.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_security_policy

**Comment by azu** [comment]
Probably, https://github.com/textlint/editor/pull/39 will fix CSP error.

**Comment by geeknees** [comment]
Thank you for the quick response. I was able to confirm the fix in my environment.
